# ============================================================
# Initialise R package + Quarto compendium project template
# Run this from the root of a freshly cloned GitHub repository
# ============================================================

# ---- 0. Project name ----

project_name <- basename(getwd())

message("Initialising project: ", project_name)

# ---- 1. Install required setup packages if missing ----

required_pkgs <- c("usethis", "devtools", "roxygen2", "renv")

missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]

if (length(missing_pkgs) > 0) {
  install.packages(missing_pkgs)
}

# ---- 2. Create minimal R package structure ----

# DESCRIPTION
if (!file.exists("DESCRIPTION")) {
  writeLines(c(
    "Package: ResearchTemplateR",
    "Title: R Package and Quarto Research Compendium",
    "Version: 0.0.0.9000",
    'Authors@R: person("Fuminari", "Miura", email = "your.email@example.com", role = c("aut", "cre"))',
    "Description: A reproducible research project combining R package functions and Quarto reports.",
    "License: MIT + file LICENSE",
    "Encoding: UTF-8",
    "Roxygen: list(markdown = TRUE)",
    "RoxygenNote: 7.3.2"
  ), "DESCRIPTION")
}

# Basic package files
dir.create("R", showWarnings = FALSE)

if (!file.exists("NAMESPACE")) {
  writeLines("# Generated by roxygen2: do not edit by hand", "NAMESPACE")
}

if (!file.exists(file.path("R", "utils.R"))) {
  writeLines(c(
    "#' Example utility function",
    "#'",
    "#' This is a placeholder function for reusable project code.",
    "#'",
    "#' @param x A numeric vector.",
    "#' @return The mean of `x`, excluding missing values.",
    "#' @export",
    "mean_na <- function(x) {",
    "  mean(x, na.rm = TRUE)",
    "}"
  ), file.path("R", "utils.R"))
}

# ---- 3. Create Quarto compendium structure ----

dirs <- c(
  "reports",
  "reports/figures",
  "reports/tables",
  "reports/output",
  "reports/scripts",
  "data",
  "data/raw",
  "data/processed",
  "docs"
)

for (d in dirs) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

# Keep otherwise-empty folders in git
gitkeep_dirs <- c(
  "reports/figures",
  "reports/tables",
  "reports/output",
  "reports/scripts",
  "data/raw",
  "data/processed",
  "docs"
)

for (d in gitkeep_dirs) {
  file.create(file.path(d, ".gitkeep"))
}

# ---- 4. Create Quarto report template ----

report_file <- file.path("reports", "Report_template.qmd")

if (!file.exists(report_file)) {
  writeLines(c(
    "---",
    paste0('title: "', project_name, ' – Report"'),
    'author: "Fuminari Miura"',
    "date: today",
    "output-dir: output",
    "format:",
    "  html:",
    "    self-contained: true",
    "    toc: true",
    "    toc-depth: 2",
    "execute:",
    "  echo: false",
    "  warning: false",
    "  message: false",
    "---",
    "",
    "# Overview",
    "",
    "Briefly describe the research question, data, model, and main outputs.",
    "",
    "# Setup",
    "",
    "```{r}",
    "library(devtools)",
    "devtools::load_all('..')",
    "```",
    "",
    "# Analysis",
    "",
    "Add analysis here, or source scripts from `reports/scripts/`.",
    "",
    "```{r}",
    "# source('scripts/01_prepare_data.R')",
    "```",
    "",
    "# Results",
    "",
    "Figures should be saved to `reports/figures/`.",
    "",
    "Tables should be saved to `reports/tables/`.",
    "",
    "# Session information",
    "",
    "```{r}",
    "sessionInfo()",
    "```"
  ), report_file)
}

# ---- 5. Create example analysis scripts ----

script_files <- list(
  "reports/scripts/01_prepare_data.R" = c(
    "# Prepare raw data and save cleaned data",
    "# Input:  data/raw/",
    "# Output: data/processed/",
    "",
    "# Example:",
    "# raw_data <- readr::read_csv('data/raw/example.csv')",
    "# readr::write_csv(clean_data, 'data/processed/clean_data.csv')"
  ),
  "reports/scripts/02_run_model.R" = c(
    "# Run model or main analysis",
    "",
    "# devtools::load_all('.')",
    "# model_output <- ..."
  ),
  "reports/scripts/03_make_figures.R" = c(
    "# Create figures and tables",
    "",
    "# ggsave('reports/figures/main_figure.png')",
    "# readr::write_csv(result_table, 'reports/tables/result_table.csv')"
  )
)

for (f in names(script_files)) {
  if (!file.exists(f)) {
    writeLines(script_files[[f]], f)
  }
}

# ---- 6. Create README (overwrite) ----

writeLines(c(
  paste0("# ", project_name),
  "",
  "This repository is a reusable template for reproducible research projects combining:",
  "",
  "- an **R package** for reusable modelling and analysis functions",
  "- a **Quarto compendium** for reports, figures, tables, and outputs",
  "",
  "---",
  "",
  "## 1. Quick start",
  "",
  "Load functions:",
  "",
  "```r",
  "devtools::load_all('.')",
  "```",
  "",
  "Run analysis:",
  "",
  "```r",
  "source('reports/scripts/01_prepare_data.R')",
  "source('reports/scripts/02_run_model.R')",
  "source('reports/scripts/03_make_figures.R')",
  "```",
  "",
  "Render report:",
  "",
  "```bash",
  "cd reports",
  "quarto render Report_template.qmd",
  "```",
  "",
  "---",
  "",
  "## 2. Project structure",
  "",
  "```",
  paste0(project_name, "/"),
  "├─ DESCRIPTION",
  "├─ NAMESPACE",
  "├─ R/                     # reusable functions",
  "├─ reports/",
  "│  ├─ Report_template.qmd",
  "│  ├─ scripts/",
  "│  ├─ figures/",
  "│  ├─ tables/",
  "│  └─ output/",
  "├─ data/",
  "│  ├─ raw/",
  "│  └─ processed/",
  "└─ docs/",
  "```",
  "",
  "---",
  "",
  "## 3. Workflow",
  "",
  "1. Put reusable functions in `R/`",
  "2. Use `reports/scripts/` for analysis steps",
  "3. Save outputs to `reports/figures` and `reports/tables`",
  "4. Generate final outputs via Quarto (`reports/`)",
  "",
  "---",
  "",
  "## 4. Reproducibility",
  "",
  "This project uses `{renv}` for reproducibility:",
  "",
  "```r",
  "renv::init()",
  "renv::snapshot()",
  "renv::restore()",
  "```",
  "",
  "Dependency discovery mode: **implicit**",
  "(scans R scripts and Quarto files)",
  "",
  "---",
  "",
  "## 5. Design philosophy",
  "",
  "This template follows a **research compendium approach**:",
  "",
  "- separation of code, data, and outputs",
  "- modular functions as an R package",
  "- analysis scripts separated from reusable code",
  "- dynamic reporting using Quarto",
  "",
  "Core principles:",
  "",
  "- one project = one repository",
  "- minimal but structured workflow",
  "- reproducibility by default",
  "",
  "---",
  "",
  "## 6. Data policy",
  "",
  "- `data/raw/`: never manually edited",
  "- `data/processed/`: generated from scripts",
  "- large datasets should not be committed",
  "",
  "---",
  "",
  "## 7. References",
  "",
  "- The Turing Way (Research compendium)",
  "  https://the-turing-way.netlify.app/reproducible-research/compendia",
  "",
  "- R Packages (Hadley Wickham)",
  "  https://r-pkgs.org/",
  "",
  "- Quarto documentation",
  "  https://quarto.org/docs/",
  "",
  "---",
  "",
  "## 8. Notes for template users",
  "",
  "After creating a new project from this template:",
  "",
  "- rename the repository",
  "- update `DESCRIPTION`",
  "- update author information",
  "- simplify structure if needed"
), "README.md")

# ---- 7. Create .gitignore ----

gitignore_lines <- c(
  ".Rproj.user/",
  ".Rhistory",
  ".RData",
  ".Ruserdata",
  ".Rbuildignore",
  ".DS_Store",
  "_freeze/",
  ".quarto/",
  "renv/library/",
  "reports/output/*",
  "!reports/output/.gitkeep",
  "reports/figures/*",
  "!reports/figures/.gitkeep",
  "reports/tables/*",
  "!reports/tables/.gitkeep",
  "data/raw/*",
  "!data/raw/.gitkeep",
  "data/processed/*",
  "!data/processed/.gitkeep"
)

writeLines(unique(gitignore_lines), ".gitignore")

# ---- 8. Optional: initialise renv ----

if (!dir.exists("renv")) {
  renv::init(bare = TRUE)
}

# ---- 9. Final message ----

message("Done.")
message("Next steps:")
message("1. Check DESCRIPTION and replace email/name if needed.")
message("2. Run devtools::document() to update NAMESPACE.")
message("3. Commit and push:")
message("   git add -A")
message("   git commit -m 'Initialise R package and Quarto research template'")
message("   git push")